export const hamburgerIcon = document.getElementById('hamburger-icon')
export const config = document.getElementById('config')
export const menu = document.getElementById('menu')
export const main = document.querySelector('.main')
export const formInput = document.querySelectorAll('.form__input-config')
export const label = document.querySelectorAll('.label')
