export const hamburgerIcon = document.getElementById('hamburger-icon')
// export const config = document.getElementById('config')
export const menu = document.getElementById('menu')
export const main = document.querySelector('.main')
// export const label = document.querySelectorAll('.label')
